### ISSUE TITLE
Migrate Packages to br-share

### ISSUE THREAD

**Issue by caelinsutch** [BytesRobotics/br-core#12]
Br_custom_messages, gscam2, and ros2_shared should all be migrated to the br-share repository. This will eliminate the need to build twice for ROS2 to get the custom message.

**Comment by caelinsutch** [comment]
**TODO**
- [ ] Clone this repository
- [ ] Checkout Development
- [ ] Create a new branch `package-migration`
- [ ] Remove submodules here for those packages: [Guide](https://gist.github.com/myusuf3/7f645819ded92bda6677)
- [ ] Checkout br-share
- [ ] Create a new branch `package-migration`
- [ ] Add the submodules into that repository
- [ ] Create a [Pull Request](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request) into development once that code is complete

**Comment by caelinsutch** [comment]
@thomasjovin What's the current status of this?

**Comment by caelinsutch** [comment]
Yeah i just did it, taking too long @thomasjovin
